In [19]:
import numpy as np
import pandas as pd

In [20]:
df = pd.read_csv("train_binary.csv")

# print(df.head())
# print(df.columns)

In [37]:

# df = df.drop(df.index[0])

x = df.drop(columns= ["label"])
y = df["label"]


In [38]:
x = np.array(x)
y = np.array(y)
print(y)

[0 1 0 ... 1 0 1]


In [60]:
def sigmoid(z):
    fwb = 1/(1+np.exp(-z))
    return fwb

loss function

In [61]:
def loss_function(x,y):
    for i in range(y.shape):
        L+= -(y[i]*np.log(sigmoi))


In [62]:
def standaradize(data):
     mu = np.mean(data,axis=0)
     std = np.std(data, axis =0)
     return (data - mu)/std , mu, std

x , x_mean, x_std = standaradize(x)
# y, y_mean, y_std = standaradize(y)

In [63]:
def logistic_regression_train(x, y, lr = 0.1, epochs= 300):
    m,n = x.shape
    w = np.zeros(n)
    b = 0

    for i in range(epochs):
        z=np.dot(x,w) + b
        y_pred = sigmoid(z)
        dj_dw = (1/m)*np.dot(x.T,(y_pred - y))
        dj_db = (1/m)*np.sum(y_pred - y)

        w = w - lr*dj_dw
        b = b - lr*dj_db
    
    return w,b


train data

In [64]:
w_new, b_new = logistic_regression_train(x, y)


predicting using trained model

In [65]:
def logistic_predict(x, w, b):
    z = np.dot(x,w) + b
    y_pred = sigmoid(z)
    return (y_pred>=0.5).astype(int)

predicting value

In [66]:
y_val_pred = logistic_predict(x,w_new,b_new)
accuracy = np.mean(y_val_pred == y )
print("Validation Accuracy:", accuracy)

print(y)

print(y_val_pred)

Validation Accuracy: 0.998519970399408
[0 1 0 ... 1 0 1]
[0 1 0 ... 1 0 1]
